### ISSUE TITLE
Short cur- hatajos de teclado

### ISSUE THREAD

**Issue by Estefania-mrkt** [ergostats/alejandria_repo#35]
Para la conclusion de la cheatsheet del tema 2 es necesario poner como tip 5 shortcuts o hatajos de teclado, los que sean mas usados.

- [x] 5 short cuts
- [ ] el tema 3 sale como infografia
- [ ] tema 4 empiezamos la proxima semana lunes 6 noviembre

**Comment by Estefania-mrkt** [comment]
Se encuentrea listo el tema 1 y tema 2 para revision y aprobacion

- [x] revisar 
- [x] aprobar
- [x] notificar si existen cambios
- [x] En donde se van a alojar para permitir la descarga? sitio web? github?drive?


enlace de visualizacion: https://www.canva.com/design/DAFxvvajoNo/lwGb_Dpk8NDDj9ZKW_ivUA/edit?utm_content=DAFxvvajoNo&utm_campaign=designshare&utm_medium=link2&utm_source=sharebutton

**Comment by AlexB4891** [comment]
Revisado y aprobado, trabajando en el enlace para colgar :)

**Comment by Estefania-mrkt** [comment]
gracias, porfavor notificarme cuando este listo el enlace, para proceder con la publicacion de los documentos

**Comment by ergostats** [comment]
https://github.com/ergostats/cheat-sheets-R/blob/main/README.md
@Estefania-mrkt listo
